{% set version = "0.10.1" %}

package:
  name: ale-py
  version: {{ version }}

source:
  url: https://github.com/Farama-Foundation/Arcade-Learning-Environment/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 7e0473de29b63f59054f8a165a968cf5a168bd9c07444d377a1f70401d268894
  patches:
    # upstream avoids ninja on windows, but we don't need to
    - patches/0001-unconditionally-use-ninja.patch
    - patches/0002-build-shared-libs.patch  # [not win]
    - patches/0003-avoid-vcpkg-toolchain.patch
    - patches/0004-fix-python-executable.patch
    - patches/0005-fix-installation-on-windows.patch
    - patches/0006-use-find-python.patch

build:
  number: 1

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - pybind11                               # [build_platform != target_platform]
    - {{ compiler('cxx') }}
    - {{ stdlib("c") }}
    # for llvm-ar
    - llvm-tools             # [osx]
    - cmake
    - ninja
  host:
    - python
    - pybind11
    - pip
    - setuptools
    - libiconv
    - sdl2
    - zlib
  run:
    - python
    # not clear where these come from, but enforced by pip check
    - importlib-metadata
    - importlib-resources
    - typing-extensions
    - numpy>=1.21.0

test:
  source_files:
    - tests/
  imports:
    - ale_py
  requires:
    - pip
    - pytest
    - gymnasium>=1.0.0
  commands:
    - pip check
    - pytest

about:
  home: https://github.com/Farama-Foundation/Arcade-Learning-Environment
  license: GPL-2.0-only
  license_family: GPL
  license_file: LICENSE.md
  summary: The Arcade Learning Environment (ALE) -- a platform for AI research.
  description: |
    The Arcade Learning Environment (ALE) is a simple framework that allows
    researchers and hobbyists to develop AI agents for Atari 2600 games.
  dev_url: https://github.com/mgbellemare/Arcade-Learning-Environment

extra:
  recipe-maintainers:
    - h-vetinari
    - Tobias-Fischer
    - pseudo-rnd-thoughts
